services:
  fiovana_v2-angular:
    image: fiovana_v2-angular:latest
    container_name: fiovana_v2-angular
    build:
      context: ../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - fiovana_v2-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  fiovana_v2-api:
    image: fiovana_v2-api:latest
    container_name: fiovana_v2-api
    hostname: fiovana_v2-api
    build:
      context: ../../
      dockerfile: src/Fiovana_v2.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=2c6a85c8-75b6-47ae-8427-fc14da1db674
      - App__SelfUrl=https://localhost:44311
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://fiovana_v2-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44388
      - App__RedirectAllowedUrls=http://localhost:4200
      - App__MVCPublicUrl=https://localhost:44375
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Fiovana_v2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44388:8081"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network
  

  fiovana_v2-web-public:
    image: fiovana_v2-web-public:latest
    container_name: fiovana_v2-web-public
    build:
      context: ../../
      dockerfile: src/Fiovana_v2.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=2c6a85c8-75b6-47ae-8427-fc14da1db674
      - App__SelfUrl=https://localhost:44375
      - App__HealthCheckUrl=http://fiovana_v2-web-public:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsOnK8s=true      
      - RemoteServices__Default__BaseUrl=http://fiovana_v2-api:8080
      - AuthServer__Authority=https://localhost:44388/
      - AuthServer__MetaAddress=http://fiovana_v2-api:8080
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Fiovana_v2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44375:8081"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network  
  db-migrator:
    image: fiovana_v2-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Fiovana_v2.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Fiovana_v2_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__Fiovana_v2_Swagger__RootUrl=https://localhost:44388
      - OpenIddict__Applications__Fiovana_v2_Web_Public__RootUrl=https://localhost:44375
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Fiovana_v2;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      
volumes:
  sqldata:
    name: fiovana_v2_sqldata
networks:
  abp-network:
    name: fiovana_v2-network
    driver: bridge
